# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Python dependencies (when backend is implemented)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for now (require manual review)
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # NPM dependencies (when frontend/Node.js services are added)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for now (require manual review)
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker dependencies (if Dockerfiles are added)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"
