name: Sync to Notion

on:
  push:
    branches: [ main ]
    paths:
      - 'pinkflow/ARCHITECTURE.md'
      - 'pinkflow/README.md'
      - '**/*.md'

env:
  NODE_VERSION: '18'

jobs:
  sync-notion:
    runs-on: ubuntu-latest
    name: Sync Documentation to Notion
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install -g @notionhq/client
          npm install -g marked
          npm install -g gray-matter

      - name: Create sync script
        run: |
          cat > sync-to-notion.js << 'EOF'
          const { Client } = require('@notionhq/client');
          const fs = require('fs');
          const path = require('path');
          const matter = require('gray-matter');
          const { marked } = require('marked');

          const notion = new Client({
            auth: process.env.NOTION_TOKEN,
          });

          const DATABASE_ID = process.env.NOTION_DATABASE_ID;

          async function syncMarkdownToNotion(filePath, title) {
            try {
              console.log(`Syncing ${filePath} to Notion...`);
              
              const content = fs.readFileSync(filePath, 'utf8');
              const { data, content: markdownContent } = matter(content);
              
              // Convert markdown to Notion blocks
              const html = marked(markdownContent);
              const blocks = convertHtmlToNotionBlocks(html);
              
              // Check if page already exists
              const existingPages = await notion.databases.query({
                database_id: DATABASE_ID,
                filter: {
                  property: 'Title',
                  title: {
                    equals: title
                  }
                }
              });
              
              if (existingPages.results.length > 0) {
                // Update existing page
                const pageId = existingPages.results[0].id;
                await notion.pages.update({
                  page_id: pageId,
                  properties: {
                    'Last Updated': {
                      date: {
                        start: new Date().toISOString()
                      }
                    }
                  }
                });
                
                // Update content
                await notion.blocks.children.clear({
                  block_id: pageId
                });
                
                await notion.blocks.children.append({
                  block_id: pageId,
                  children: blocks
                });
                
                console.log(`✅ Updated existing page: ${title}`);
              } else {
                // Create new page
                await notion.pages.create({
                  parent: {
                    database_id: DATABASE_ID
                  },
                  properties: {
                    'Title': {
                      title: [
                        {
                          text: {
                            content: title
                          }
                        }
                      ]
                    },
                    'Type': {
                      select: {
                        name: 'Documentation'
                      }
                    },
                    'Status': {
                      select: {
                        name: 'Active'
                      }
                    },
                    'Last Updated': {
                      date: {
                        start: new Date().toISOString()
                      }
                    }
                  },
                  children: blocks
                });
                
                console.log(`✅ Created new page: ${title}`);
              }
            } catch (error) {
              console.error(`❌ Failed to sync ${filePath}:`, error.message);
            }
          }

          function convertHtmlToNotionBlocks(html) {
            const blocks = [];
            const lines = html.split('\n');
            
            for (const line of lines) {
              if (line.trim() === '') continue;
              
              if (line.startsWith('<h1>')) {
                blocks.push({
                  object: 'block',
                  type: 'heading_1',
                  heading_1: {
                    rich_text: [{
                      type: 'text',
                      text: { content: line.replace(/<h1>(.*?)<\/h1>/, '$1') }
                    }]
                  }
                });
              } else if (line.startsWith('<h2>')) {
                blocks.push({
                  object: 'block',
                  type: 'heading_2',
                  heading_2: {
                    rich_text: [{
                      type: 'text',
                      text: { content: line.replace(/<h2>(.*?)<\/h2>/, '$1') }
                    }]
                  }
                });
              } else if (line.startsWith('<h3>')) {
                blocks.push({
                  object: 'block',
                  type: 'heading_3',
                  heading_3: {
                    rich_text: [{
                      type: 'text',
                      text: { content: line.replace(/<h3>(.*?)<\/h3>/, '$1') }
                    }]
                  }
                });
              } else if (line.startsWith('<p>')) {
                blocks.push({
                  object: 'block',
                  type: 'paragraph',
                  paragraph: {
                    rich_text: [{
                      type: 'text',
                      text: { content: line.replace(/<p>(.*?)<\/p>/, '$1') }
                    }]
                  }
                });
              } else if (line.startsWith('<code>')) {
                blocks.push({
                  object: 'block',
                  type: 'code',
                  code: {
                    rich_text: [{
                      type: 'text',
                      text: { content: line.replace(/<code>(.*?)<\/code>/, '$1') }
                    }],
                    language: 'javascript'
                  }
                });
              } else {
                // Default to paragraph
                blocks.push({
                  object: 'block',
                  type: 'paragraph',
                  paragraph: {
                    rich_text: [{
                      type: 'text',
                      text: { content: line }
                    }]
                  }
                });
              }
            }
            
            return blocks;
          }

          // Sync key files
          async function main() {
            const filesToSync = [
              { path: 'pinkflow/ARCHITECTURE.md', title: 'MBTQ Universe Architecture' },
              { path: 'pinkflow/README.md', title: 'Pinkflow CLI Documentation' }
            ];
            
            for (const file of filesToSync) {
              if (fs.existsSync(file.path)) {
                await syncMarkdownToNotion(file.path, file.title);
              } else {
                console.log(`⚠️  File not found: ${file.path}`);
              }
            }
          }

          main().catch(console.error);
          EOF

      - name: Sync to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          node sync-to-notion.js

      - name: Create sync report
        if: always()
        run: |
          echo "## 📝 Notion Sync Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Documentation synced to Notion**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📋 **Files synced:**" >> $GITHUB_STEP_SUMMARY
          echo "- pinkflow/ARCHITECTURE.md" >> $GITHUB_STEP_SUMMARY
          echo "- pinkflow/README.md" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔗 **Notion Database:** ${{ secrets.NOTION_DATABASE_ID }}" >> $GITHUB_STEP_SUMMARY 